INSERT INTO facultades (id_facultad, id_institucion, nombre_facultad, director) VALUES
(1, 1, 'Ingeniería', 'Carlos Gómez'),
(2, 2, 'Ciencias Humanas', 'Laura Martínez'),
(3, 3, 'Medicina', 'Juan Pérez'),
(4, 4, 'Artes Integradas', 'Diana Torres'),
(5, 5, 'Ciencias Naturales', 'Jorge Castillo'),
(6, 6, 'Ciencias Sociales', 'Camila Rojas'),
(7, 7, 'Ciencias Económicas y Administrativas', 'Luis Rodríguez'),
(8, 8, 'Ingeniería y Ciencias', 'María Fernández'),
(9, 9, 'Derecho', 'José Herrera'),
(10, 10, 'Comunicación Social', 'Paola Sánchez'),
(11, 11, 'Ciencias de la Salud', 'Andrés Salazar'),
(12, 12, 'Ciencias Exactas', 'Sofía Ramírez'),
(13, 13, 'Educación y Pedagogía', 'Ricardo Vargas'),
(14, 14, 'Ingenierías', 'Natalia Castro'),
(15, 15, 'Formación de Docentes', 'Mónica Pineda'),
(16, 16, 'Ciencias Básicas', 'David Ortega'),
(17, 17, 'Psicología', 'Juliana Gómez'),
(18, 18, 'Filosofía y Letras', 'Pedro Morales'),
(19, 19, 'Ciencias Marinas', 'Carolina Muñoz'),
(20, 20, 'Ingeniería y Tecnología', 'Samuel Guerrero');

