INSERT INTO asignaturas (id_asignatura, id_programa, nombre_asignatura, creditos, modalidad) VALUES
(1, 1, 'Electrónica Analógica', 3, 'Presencial'),
(2, 1, 'Circuitos Digitales', 3, 'Presencial'),
(3, 2, 'Programación I', 3, 'Presencial'),
(4, 2, 'Base de Datos 1', 3, 'Virtual'),
(5, 3, 'Diseño Lógico Programable', 3, 'Presencial'),
(6, 3, 'Microcontroladores', 3, 'Presencial'),
(7, 4, 'Redes de Computadores', 3, 'Presencial'),
(8, 4, 'Sistemas de Comunicación', 3, 'Mixta'),
(9, 5, 'Seguridad en Redes', 3, 'Virtual'),
(10, 5, 'Protocolos de Comunicación', 3, 'Presencial'),
(11, 6, 'Base de Datos 2', 3, 'Virtual'),
(12, 6, 'Ingeniería de Requisitos', 3, 'Presencial'),
(13, 7, 'Teoría Antropológica', 3, 'Presencial'),
(14, 7, 'Métodos Etnográficos', 2, 'Virtual'),
(15, 8, 'Historia de Europa Moderna', 3, 'Virtual'),
(16, 8, 'Colonia y República en América Latina', 3, 'Virtual'),
(17, 9, 'Anatomía Humana', 4, 'Presencial'),
(18, 9, 'Fisiología', 4, 'Presencial'),
(19, 10, 'Técnicas Quirúrgicas', 4, 'Presencial'),
(20, 10, 'Farmacología Clínica', 3, 'Mixta'),
(21, 11, 'Pediatría Preventiva', 3, 'Presencial'),
(22, 11, 'Neonatología', 3, 'Presencial'),
(23, 12, 'Epidemiología', 3, 'Virtual'),
(24, 12, 'Salud Pública', 3, 'Mixta'),
(25, 13, 'Teoría Musical', 2, 'Presencial'),
(26, 13, 'Armonía I', 2, 'Presencial'),
(27, 14, 'Composición I', 3, 'Presencial'),
(28, 14, 'Software Musical', 2, 'Virtual'),
(29, 15, 'Actuación I', 3, 'Presencial'),
(30, 15, 'Expresión Corporal', 2, 'Presencial'),
(31, 16, 'Puesta en Escena', 3, 'Presencial'),
(32, 16, 'Estética Teatral', 3, 'Virtual'),
(33, 17, 'Genética Molecular', 3, 'Presencial'),
(34, 17, 'Bioquímica', 3, 'Presencial'),
(35, 18, 'Ingeniería Genética', 3, 'Presencial'),
(36, 18, 'Cultivo Celular', 3, 'Presencial'),
(37, 19, 'Química Orgánica', 4, 'Presencial'),
(38, 19, 'Procesos Químicos Industriales', 3, 'Presencial'),
(39, 20, 'Laboratorio de Química', 3, 'Mixta'),
(40, 20, 'Química Ambiental', 3, 'Virtual'),
(41, 21, 'Estructura Social Colombiana', 3, 'Presencial'),
(42, 21, 'Sociología Política', 3, 'Virtual'),
(43, 22, 'Sociología del Conflicto Armado', 3, 'Virtual'),
(44, 22, 'Justicia Transicional', 3, 'Virtual'),
(45, 23, 'Planeación Social', 3, 'Virtual'),
(46, 23, 'Intervención Comunitaria', 3, 'Mixta'),
(47, 24, 'Gestión de Proyectos Sociales', 3, 'Mixta'),
(48, 24, 'Indicadores Sociales', 3, 'Virtual'),
(49, 25, 'Contabilidad General', 3, 'Presencial'),
(50, 25, 'Normas Internacionales de Información Financiera', 3, 'Presencial'),
(51, 26, 'Fundamentos de Administración', 3, 'Presencial'),
(52, 26, 'Gestión de Talento Humano', 3, 'Virtual'),
(53, 27, 'Emprendimiento e Innovación', 3, 'Mixta'),
(54, 27, 'Planeación Estratégica', 3, 'Presencial'),
(55, 28, 'Constitución Colombiana', 3, 'Presencial'),
(56, 28, 'Derechos Fundamentales', 3, 'Virtual'),
(57, 29, 'Redacción Periodística', 3, 'Presencial'),
(58, 29, 'Ética de la Comunicación', 2, 'Mixta'),
(59, 30, 'Cálculo Diferencial', 4, 'Virtual'),
(60, 30, 'Didáctica de las Matemáticas', 3, 'Virtual');

