INSERT INTO ira (id_ira, id_proyecto, titulo_ira, estado) VALUES
(1, 1, 'Informe de Redes Inalámbricas', 'Finalizado'),
(2, 2, 'Informe Sistema Inventario', 'Finalizado'),
(3, 3, 'Informe Sociología Urbana', 'Finalizado'),
(4, 4, 'Informe Microservicios Docker', 'Finalizado'),
(5, 5, 'Informe Gestión Académica', 'Finalizado'),
(6, 6, 'Informe Composición Musical', 'Finalizado'),
(7, 7, 'Informe Enfermedades Respiratorias', 'Finalizado'),
(8, 8, 'Informe Gestión Proyectos PIA', 'Finalizado'),
(9, 9, 'Informe Diseño Interfaces', 'Finalizado'),
(10, 10, 'Informe Simulación Redes NS3', 'Finalizado'),
(11, 11, 'Informe Visualización Datos Sociales', 'Finalizado'),
(12, 12, 'Informe Plataforma Historia', 'Finalizado'),
(13, 13, 'Informe Diagnóstico Médico', 'Finalizado'),
(14, 14, 'Informe Consumo Energético IoT', 'Finalizado'),
(15, 15, 'Informe Red Social Académica', 'Finalizado'),
(16, 16, 'Informe Evaluación Docente', 'Finalizado'),
(17, 17, 'Informe Algoritmos Búsqueda', 'Finalizado'),
(18, 18, 'Informe IA Reconocimiento Facial', 'Finalizado'),
(19, 19, 'Informe Videojuego Matemático', 'Finalizado'),
(20, 20, 'Informe Base Datos Biblioteca', 'Finalizado'),
(21, 21, 'Informe Blockchain Académico', 'Finalizado'),
(22, 22, 'Informe Control Acceso RFID', 'Finalizado'),
(23, 23, 'Informe Aprendizaje Virtual', 'Finalizado'),
(24, 24, 'Informe Seguimiento Nutricional', 'Finalizado'),
(25, 25, 'Informe Prototipo Dron Autónomo', 'Finalizado'),
(26, 26, 'Informe Geolocalización Transporte', 'Finalizado'),
(27, 27, 'Informe Opinión Pública', 'Finalizado'),
(28, 28, 'Informe Recomendación Cursos', 'Finalizado'),
(29, 29, 'Informe Control Domótico', 'Finalizado'),
(30, 30, 'Informe Chatbot Soporte', 'Finalizado'),
(31, 31, 'Informe Redes Neuronales', 'Finalizado'),
(32, 32, 'Informe Gestión Tiempo', 'Finalizado'),
(33, 33, 'Informe Repositorio Proyectos', 'Finalizado'),
(34, 34, 'Informe Voluntariado Estudiantil', 'Finalizado'),
(35, 35, 'Informe Tutorías en Línea', 'Finalizado'),
(36, 36, 'Informe Monitoreo Ambiental', 'Finalizado'),
(37, 37, 'Informe Logística Académica', 'Finalizado'),
(38, 38, 'Informe Compresión Imágenes', 'Finalizado'),
(39, 39, 'Informe Encuestas Automatizadas', 'Finalizado'),
(40, 40, 'Informe ERP Gestión Universitaria', 'Finalizado'),
(41, 41, 'Informe Notificación Móvil', 'Finalizado'),
(42, 42, 'Informe Gestión Grupos Estudio', 'Finalizado'),
(43, 43, 'Informe Eventos Académicos', 'Finalizado'),
(44, 44, 'Informe Control Plagio', 'Finalizado'),
(45, 45, 'Informe Gestión Citas Médicas', 'Finalizado'),
(46, 46, 'Informe Registro Actividades', 'Finalizado'),
(47, 47, 'Informe Seguimiento Proyectos', 'Finalizado'),
(48, 48, 'Informe Simulador Laboratorios', 'Finalizado'),
(49, 49, 'Informe Wiki Académico', 'Finalizado'),
(50, 50, 'Informe Trayectorias Académicas', 'Finalizado');
