INSERT INTO era (id_era, id_proyecto, titulo_era, resultado, estado) VALUES
(1, 1, 'Evaluación de Optimización de Redes', 'Se logró mejorar la eficiencia en un 15% mediante ajustes en la configuración de nodos.', 'Finalizado'),
(2, 2, 'Evaluación Sistema Inventario Web', 'El sistema permite gestión eficiente de inventario con reportes dinámicos y alta disponibilidad.', 'Finalizado'),
(3, 3, 'Evaluación Análisis Sociológico', 'Se identificaron patrones sociales clave que apoyan futuras políticas comunitarias.', 'Finalizado'),
(4, 4, 'Evaluación Implementación Docker', 'Los microservicios desplegados con Docker mostraron escalabilidad y rapidez en respuesta.', 'Finalizado'),
(5, 5, 'Evaluación App Gestión Académica', 'La aplicación mejora la organización de tareas con un incremento del 25% en cumplimiento.', 'Finalizado'),
(6, 6, 'Evaluación Composición Musical', 'Se catalogaron y analizaron 50 piezas contemporáneas con tendencias innovadoras.', 'Finalizado'),
(7, 7, 'Evaluación Modelo Predictivo Enfermedades', 'Modelo predictivo alcanzó un 85% de precisión en detección temprana.', 'Finalizado'),
(8, 8, 'Evaluación Sistema Gestión PIA', 'Sistema facilita la gestión de proyectos con interfaz intuitiva y reportes automatizados.', 'Finalizado'),
(9, 9, 'Evaluación Diseño Interfaces Usables', 'Interfaz diseñada mostró mayor accesibilidad para adultos mayores en pruebas piloto.', 'Finalizado'),
(10, 10, 'Evaluación Simulación Redes NS3', 'Simulaciones demostraron mejoras en topologías y reducción de latencia.', 'Finalizado'),
(11, 11, 'Evaluación Visualización Datos Sociales', 'Herramienta interactiva permitió mejor comprensión de datos demográficos.', 'Finalizado'),
(12, 12, 'Evaluación Plataforma Virtual Historia', 'La plataforma potenció el aprendizaje histórico con recursos multimedia diversos.', 'Finalizado'),
(13, 13, 'Evaluación Sistema Experto Diagnóstico', 'Sistema experto ofreció diagnósticos confiables con tasa de error menor al 5%.', 'Finalizado'),
(14, 14, 'Evaluación Optimización Consumo IoT', 'Se lograron ahorros significativos de energía en dispositivos IoT implementados.', 'Finalizado'),
(15, 15, 'Evaluación Red Social Académica', 'La red social facilitó la colaboración estudiantil incrementando la participación en un 40%.', 'Finalizado'),
(16, 16, 'Evaluación Herramienta Evaluación Docente', 'Herramienta optimiza la evaluación con métricas precisas y reportes detallados.', 'Finalizado'),
(17, 17, 'Evaluación Eficiencia Algoritmos Búsqueda', 'Algoritmos implementados mejoraron tiempos de búsqueda en bases de datos.', 'Finalizado'),
(18, 18, 'Evaluación IA Reconocimiento Facial', 'El sistema mostró alta precisión en reconocimiento bajo condiciones diversas.', 'Finalizado'),
(19, 19, 'Evaluación Videojuego Educativo Matemático', 'Videojuego aumentó la comprensión de conceptos matemáticos en un 30%.', 'Finalizado'),
(20, 20, 'Evaluación Diseño Base de Datos Biblioteca', 'Base de datos mejoró la organización y acceso a recursos bibliográficos.', 'Finalizado'),
(21, 21, 'Evaluación Blockchain Registros Académicos', 'Blockchain garantizó seguridad y trazabilidad en registros académicos.', 'Finalizado'),
(22, 22, 'Evaluación Sistema Control Acceso RFID', 'Sistema RFID funcionó eficientemente en control de acceso con baja tasa de errores.', 'Finalizado'),
(23, 23, 'Evaluación Estrategias Aprendizaje Virtual', 'Se identificaron métodos efectivos para mejorar el aprendizaje remoto.', 'Finalizado'),
(24, 24, 'Evaluación Seguimiento Nutricional', 'App facilitó el seguimiento personalizado y mejoró hábitos alimenticios.', 'Finalizado'),
(25, 25, 'Evaluación Prototipo Dron Autónomo', 'Dron demostró navegación autónoma con alta precisión en reconocimiento.', 'Finalizado'),
(26, 26, 'Evaluación App Geolocalización Transporte', 'Aplicación mejoró la movilidad y seguimiento de transporte universitario.', 'Finalizado'),
(27, 27, 'Evaluación Análisis Opinión Pública', 'Se detectaron tendencias y opiniones relevantes en grupos estudiantiles.', 'Finalizado'),
(28, 28, 'Evaluación Sistema Recomendación Cursos', 'Sistema recomendó cursos personalizados aumentando la satisfacción estudiantil.', 'Finalizado'),
(29, 29, 'Evaluación Sistema Control Domótico', 'Sistema domótico mostró eficiencia en control y ahorro energético.', 'Finalizado'),
(30, 30, 'Evaluación Chatbot Soporte Académico', 'Chatbot brindó respuestas rápidas y mejoró la experiencia de soporte.', 'Finalizado'),
(31, 31, 'Evaluación Simulador Redes Neuronales', 'Simulador facilitó el aprendizaje y experimentación de redes neuronales.', 'Finalizado'),
(32, 32, 'Evaluación Herramienta Gestión Tiempo', 'Herramienta aumentó la productividad y organización estudiantil.', 'Finalizado'),
(33, 33, 'Evaluación Repositorio Académico Proyectos', 'Repositorio centralizó proyectos con acceso sencillo y seguro.', 'Finalizado'),
(34, 34, 'Evaluación App Voluntariado Estudiantil', 'App incentivó la participación en actividades voluntarias.', 'Finalizado'),
(35, 35, 'Evaluación Aplicación Tutorías en Línea', 'Aplicación mejoró la comunicación y seguimiento en tutorías.', 'Finalizado'),
(36, 36, 'Evaluación Sistema Monitoreo Ambiental', 'Sistema IoT permitió monitoreo en tiempo real con alta precisión.', 'Finalizado'),
(37, 37, 'Evaluación App Logística Académica', 'App optimizó la logística y coordinación de actividades académicas.', 'Finalizado'),
(38, 38, 'Evaluación Algoritmos Compresión Imágenes', 'Algoritmos redujeron el tamaño de imágenes manteniendo calidad.', 'Finalizado'),
(39, 39, 'Evaluación Sistema Encuestas Automatizadas', 'Sistema agilizó la recopilación y análisis de datos de encuestas.', 'Finalizado'),
(40, 40, 'Evaluación ERP Gestión Universitaria', 'ERP mejoró procesos administrativos con integración completa.', 'Finalizado'),
(41, 41, 'Evaluación Sistema Notificación Móvil', 'Sistema notificó eventos con eficacia y buena aceptación.', 'Finalizado'),
(42, 42, 'Evaluación App Gestión Grupos Estudio', 'App facilitó la coordinación y comunicación en grupos de estudio.', 'Finalizado'),
(43, 43, 'Evaluación Plataforma Eventos Académicos', 'Plataforma soportó eventos virtuales con alta concurrencia.', 'Finalizado'),
(44, 44, 'Evaluación Sistema Control Plagio', 'Sistema detectó plagios con alta tasa de aciertos.', 'Finalizado'),
(45, 45, 'Evaluación Gestión Citas Médicas', 'Sistema optimizó la gestión y programación de citas médicas.', 'Finalizado'),
(46, 46, 'Evaluación App Registro Actividades', 'App permitió registro eficiente de actividades extracurriculares.', 'Finalizado'),
(47, 47, 'Evaluación Seguimiento Proyectos Grado', 'Sistema brindó seguimiento puntual a proyectos de grado.', 'Finalizado'),
(48, 48, 'Evaluación Simulador Virtual Laboratorios', 'Simulador facilitó la experimentación remota en física.', 'Finalizado'),
(49, 49, 'Evaluación Wiki Académico Colaborativo', 'Wiki permitió colaboración y acceso rápido a información académica.', 'Finalizado'),
(50, 50, 'Evaluación Visualización Trayectorias Académicas', 'Visualización ayudó a entender el progreso académico de estudiantes.', 'Finalizado');
