INSERT INTO programas (id_programa, cod_programa, id_departamento, nombre_programa, nivel, modalidad) VALUES
(1, 'PROG001', 1, 'Ingeniería Electrónica', 'Pregrado', 'Presencial'),
(2, 'PROG002', 1, 'Tecnología en Desarrollo de Software', 'Tecnológico', 'Virtual'),
(3, 'PROG003', 1, 'Sistemas Digitales Avanzados', 'Posgrado', 'Presencial'),
(4, 'PROG004', 2, 'Ingeniería en Telecomunicaciones', 'Pregrado', 'Presencial'),
(5, 'PROG005', 2, 'Redes y Conectividad', 'Tecnológico', 'Mixta'),
(6, 'PROG006', 2, 'Ingeniería de Software', 'Pregrado', 'Presencial'),
(7, 'PROG007', 3, 'Antropología Social', 'Pregrado', 'Presencial'),
(8, 'PROG008', 4, 'Historia Moderna', 'Pregrado', 'Virtual'),
(9, 'PROG009', 5, 'Medicina General', 'Pregrado', 'Presencial'),
(10, 'PROG010', 5, 'Cirugía General', 'Posgrado', 'Presencial'),
(11, 'PROG011', 6, 'Pediatría Clínica', 'Posgrado', 'Presencial'),
(12, 'PROG012', 6, 'Salud Comunitaria', 'Pregrado', 'Presencial'),
(13, 'PROG013', 7, 'Música', 'Pregrado', 'Presencial'),
(14, 'PROG014', 7, 'Composición Musical', 'Pregrado', 'Presencial'),
(15, 'PROG015', 8, 'Artes Escénicas', 'Pregrado', 'Presencial'),
(16, 'PROG016', 8, 'Dirección Teatral', 'Posgrado', 'Presencial'),
(17, 'PROG017', 9, 'Biología Molecular', 'Pregrado', 'Presencial'),
(18, 'PROG018', 9, 'Biotecnología', 'Pregrado', 'Presencial'),
(19, 'PROG019', 10, 'Química Industrial', 'Pregrado', 'Presencial'),
(20, 'PROG020', 10, 'Química Aplicada', 'Pregrado', 'Virtual'),
(21, 'PROG021', 11, 'Sociología Aplicada', 'Pregrado', 'Presencial'),
(22, 'PROG022', 11, 'Sociología del Conflicto', 'Posgrado', 'Virtual'),
(23, 'PROG023', 12, 'Trabajo Social Comunitario', 'Pregrado', 'Virtual'),
(24, 'PROG024', 12, 'Gestión Social', 'Tecnológico', 'Mixta'),
(25, 'PROG025', 13, 'Contaduría Pública', 'Pregrado', 'Presencial'),
(26, 'PROG026', 14, 'Administración de Empresas', 'Pregrado', 'Mixta'),
(27, 'PROG027', 14, 'Gestión Empresarial', 'Tecnológico', 'Virtual'),
(28, 'PROG028', 17, 'Derecho Constitucional', 'Pregrado', 'Presencial'),
(29, 'PROG029', 18, 'Periodismo', 'Pregrado', 'Presencial'),
(30, 'PROG030', 20, 'Licenciatura en Matemáticas', 'Pregrado', 'Virtual');


