INSERT INTO departamentos (id_departamento, id_facultad, nombre_departamento, jefe_departamento) VALUES
(1, 1, 'Sistemas Digitales', 'Álvaro Gómez'),
(2, 1, 'Telecomunicaciones', 'María Rincón'),
(3, 2, 'Antropología', 'Luis Torres'),
(4, 2, 'Historia', 'Paula Mendoza'),
(5, 3, 'Cirugía', 'Carlos Díaz'),
(6, 3, 'Pediatría', 'Verónica Suárez'),
(7, 4, 'Música', 'Daniela Ruiz'),
(8, 4, 'Artes Escénicas', 'Jorge Gutiérrez'),
(9, 5, 'Biología', 'Sandra López'),
(10, 5, 'Química', 'Eduardo Herrera'),
(11, 6, 'Sociología', 'Nicolás Castillo'),
(12, 6, 'Trabajo Social', 'Andrea Ramírez'),
(13, 7, 'Contaduría Pública', 'Miguel Ortega'),
(14, 7, 'Administración de Empresas', 'Laura Quintero'),
(15, 8, 'Ingeniería Electrónica', 'Jesús Morales'),
(16, 8, 'Ingeniería Mecánica', 'Tatiana Guzmán'),
(17, 9, 'Derecho Público', 'Felipe Acosta'),
(18, 10, 'Periodismo', 'Camilo Vargas'),
(19, 11, 'Enfermería', 'Natalia Sánchez'),
(20, 12, 'Matemáticas', 'Diana Cabrera');

